import 'package:cloud_firestore/cloud_firestore.dart';
import 'bot_service.dart';

class BotSeedData {
  static const List<BotArchetype> archetypes = [
    BotArchetype(
      id: 'calm_monk',
      displayName: 'Calm Monk',
      description: 'Peaceful wisdom for a centered mind.',
      messages: [
        'Breathe slowly today. Calm attention brings clear action.',
        'Begin the day with quiet focus and a steady mind.',
        'Peace grows when you move through the day with intention.',
        'Do one thing today with full presence.',
        'A calm mind turns ordinary moments into meaningful ones.',
        'Let patience guide your actions today.',
        'Progress happens one peaceful step at a time.',
        'Choose clarity over hurry today.',
        'Your breath can return you to calm at any moment.',
        'Move through the day gently and with purpose.',
        'Quiet effort creates steady progress.',
        'Focus on what you can do calmly today.',
        'A clear mind sees the right path forward.',
        'Let today be guided by patience and steady effort.',
        'Small mindful actions create lasting change.',
        'Breathe, focus, and begin again.',
        'Peaceful effort carries great strength.',
        'Calm attention brings wisdom to your work.',
        'Slow down enough to notice what matters.',
        'Choose thoughtful action over rushed reaction.',
        'Let calm guide your decisions today.',
        'Each breath is a chance to begin again.',
        'Move forward with quiet determination.',
        'A peaceful mind makes better choices.',
        'Focus gently on what matters most today.',
        'Steady effort is stronger than sudden bursts.',
        'Choose patience as your guide today.',
        'Calm effort leads to meaningful progress.',
        'Let clarity shape your actions.',
        'Approach the day with a quiet mind.',
        'Listen carefully to the moment in front of you.',
        'Let go of worry and focus on the next step.',
        'A calm mind sees opportunity clearly.',
        'Give today your quiet attention.',
        'Focus on the work that brings growth.',
        'Inner calm strengthens outer action.',
        'One peaceful step forward is enough today.',
        'Let your actions be thoughtful and steady.',
        'Simplicity brings clarity to your day.',
        'Quiet discipline builds strong foundations.',
        'Breathe deeply and move forward with purpose.',
        'Calm focus makes hard things possible.',
        'Choose presence instead of distraction.',
        'Progress grows from patient effort.',
        'Let your mind settle before making decisions.',
        'Gentle persistence moves mountains.',
        'Keep your attention on what truly matters.',
        'Peaceful focus improves everything you do.',
        'Move through challenges with calm strength.',
        'Your breath can guide you back to balance.',
        'Let today unfold with mindful effort.',
        'Focus on steady improvement.',
        'Quiet reflection leads to wise action.',
        'Choose calm over chaos today.',
        'A peaceful mind works more clearly.',
        'Let patience shape your progress.',
        'Approach the day with quiet confidence.',
        'Simple steps lead to meaningful change.',
        'Balance effort with calm awareness.',
        'A calm start creates a focused day.',
        'Give your full attention to the task before you.',
        'Let clarity guide your next step.',
        'Work steadily and without rush.',
        'Calm discipline creates lasting success.',
        'Let your actions reflect your values today.',
        'Quiet strength carries you forward.',
        'Focus gently but firmly on progress.',
        'A steady mind leads to steady growth.',
        'Choose thoughtful effort today.',
        'Let patience guide your work.',
        'Keep your attention on the present moment.',
        'Calm effort leads to wise results.',
        'Breathe deeply and begin again.',
        'Progress arrives through quiet consistency.',
        'Let your work today be mindful and sincere.',
        'Calm awareness improves every choice.',
        'Move forward with patience and clarity.',
        'A peaceful approach creates strong results.',
        'Focus on what you can improve today.',
        'Quiet determination creates lasting change.',
        'Let calm energy guide your efforts.',
        'Give the day your steady attention.',
        'A focused mind sees simple solutions.',
        'Choose calm persistence over frustration.',
        'Let each step today be thoughtful.',
        'Peace grows through mindful action.',
        'Calm discipline strengthens your path.',
        'Progress begins with quiet intention.',
        'Approach challenges with steady breath.',
        'Let calm awareness shape your work.',
        'Focus on the next peaceful step.',
        'Let your mind be steady and clear.',
        'Quiet effort brings meaningful progress.',
        'Move through the day with mindful purpose.',
        'Calm attention creates strong results.',
        'Choose patience when things feel rushed.',
        'Let balance guide your decisions.',
        'Work with calm focus and gentle strength.',
        'Each quiet effort builds a better tomorrow.',
        'End the day with gratitude for the progress you made.',
      ],
    ),
    BotArchetype(
      id: 'champion_coach',
      displayName: 'Champion Coach',
      description: 'High-energy motivation to unlock your best.',
      messages: [
        'Are you preparing today like a champion or hoping to get lucky tomorrow?',
        'What did you do this morning that your opponent didn’t?',
        'Are you chasing comfort or chasing greatness?',
        'Did you win the first battle of the day—getting out of bed with purpose?',
        'What separates you from average today?',
        'Are you training your body or training your excuses?',
        'When adversity hits, do you tighten your focus or look for a way out?',
        'Are you competing with others or competing with your best self?',
        'What would a champion do with the next hour of your life?',
        'Are you thinking like a player or thinking like a leader?',
        'Did you give your body a reason to grow stronger today?',
        'Are you training with intensity or just going through the motions?',
        'When the workout gets hard, do you speed up or slow down?',
        'Did you push past the moment where most people quit?',
        'Are you building strength that shows up when the pressure hits?',
        'What part of your body needs more discipline today?',
        'Did you fuel your body like an athlete or like a spectator?',
        'Are you recovering like a professional or neglecting your preparation?',
        'Did you leave something in the tank—or did you empty it?',
        'If the game were today, would your body be ready?',
        'What habit today is building the champion you want to become?',
        'Are you keeping the promises you made to yourself?',
        'Did you show up early or arrive barely on time?',
        'Are you controlling your day or letting distractions control you?',
        'Are you disciplined when nobody is watching?',
        'What small detail are you ignoring that could cost you later?',
        'Did you earn your rest today?',
        'Are you stacking good days or repeating the same mistakes?',
        'Did you improve by 1% today?',
        'Are you building consistency or chasing motivation?',
        'Are you lifting the people around you or draining their energy?',
        'Who needs your encouragement today?',
        'Are you setting the pace for your team?',
        'What example are you setting when things get difficult?',
        'Are you communicating like a leader?',
        'Who is watching how you handle adversity?',
        'Did you bring energy into the room today?',
        'Are you leading by effort or by words?',
        'Would your teammates trust your preparation?',
        'What standard are you holding everyone to today?',
        'Do you know your opponent’s strengths today?',
        'What weakness can you exploit with better preparation?',
        'Are you studying the game or guessing your way through it?',
        'What adjustment will you make if the first plan fails?',
        'Did you review the film of your mistakes?',
        'Are you anticipating challenges or reacting too late?',
        'What play will you call when pressure rises?',
        'Have you practiced the situation before it happens?',
        'Do you have a backup plan ready?',
        'Are you prepared for the unexpected?',
        'When fatigue hits, what voice do you listen to?',
        'Are you stronger than the excuses in your mind?',
        'Can you stay calm when chaos begins?',
        'When things go wrong, do you regroup or unravel?',
        'Are you prepared to outlast everyone else?',
        'Do setbacks sharpen your focus or break your confidence?',
        'Are you comfortable being uncomfortable?',
        'What pressure are you willing to embrace today?',
        'Did you train your mind as hard as your body?',
        'Are you willing to do the difficult work others avoid?',
        'What does success look like at the end of today?',
        'Did you take a step toward the championship you want?',
        'Are you playing the long game or chasing quick wins?',
        'What legacy are you building with your effort today?',
        'Are you proud of the work you did this week?',
        'Did you leave your comfort zone behind?',
        'What victory can you earn today?',
        'Are you learning from every rep you take?',
        'Are you moving closer to mastery?',
        'What would the best version of you do right now?',
        'Did you own your mistakes today?',
        'Are you blaming circumstances or building solutions?',
        'What responsibility are you avoiding?',
        'Are you accountable to your standards?',
        'Who can hold you accountable today?',
        'Are you reviewing your performance honestly?',
        'Did you correct yesterday’s errors?',
        'Are you improving the areas you struggle with most?',
        'Did you accept feedback like a professional?',
        'Are you willing to be coached?',
        'Are you contributing to a winning culture today?',
        'Did you encourage someone who needed it?',
        'Are you strengthening the team or focusing only on yourself?',
        'What energy are you bringing to the locker room today?',
        'Are you dependable when it matters most?',
        'Are you helping the team grow stronger?',
        'What sacrifice will you make for the group today?',
        'Are you building trust with your actions?',
        'Did you celebrate someone else\'s success today?',
        'Are you making the team better?',
        'Are you preparing like the championship is tomorrow?',
        'Did you earn the right to win today?',
        'What separates champions from everyone else today?',
        'Are you willing to do what others won’t?',
        'Did you compete with relentless effort?',
        'Are you focused on the next play or the last mistake?',
        'What would a champion do with the next five minutes?',
        'Did you give everything you had today?',
        'Are you ready when the opportunity comes?',
        'Did you leave the field better than you found it?',
      ],
    ),
    BotArchetype(
      id: 'drill_sergeant',
      displayName: 'Drill Sergeant',
      description: 'No excuses, no shortcuts — results only.',
      messages: [
        'Stop thinking. Start moving.',
        'Excuses don’t move goals. Action does.',
        'Do it now. Not later.',
        'You don’t need permission. Execute.',
        'Discomfort is not danger. Move.',
        'Quit negotiating. Begin.',
        'This is not complicated. Do the work.',
        'Momentum starts with action. Go.',
        'Waiting is a decision. Choose action.',
        'Get out of your head and into motion.',
        'No more planning. Execute.',
        'Results don’t care how you feel.',
        'You said this mattered. Prove it.',
        'Action first. Complaints later.',
        'Stand up and start.',
        'Enough delay. Move.',
        'Focus. Execute.',
        'Stop scrolling. Start working.',
        'Do the hardest part first.',
        'Energy follows action. Go.',
        'Your comfort zone is not the objective.',
        'Start sloppy. Improve later.',
        'You don’t need motivation. You need discipline.',
        'Move your body. Move the task.',
        'Zero drama. Full effort.',
        'Finish something today.',
        'Talk less. Do more.',
        'This won’t do itself.',
        'Begin now.',
        'No excuses accepted.',
        'Discipline beats motivation.',
        'Get uncomfortable on purpose.',
        'Action creates clarity.',
        'Quit waiting for the mood.',
        'You are capable. Prove it.',
        'Stop avoiding. Start attacking.',
        'Do one thing. Then another.',
        'Progress requires pressure. Apply it.',
        'Stand firm. Execute.',
        'End the delay.',
        'Start before you’re ready.',
        'Your future self is watching.',
        'Do the work you’re resisting.',
        'Enough analysis. Action.',
        'Move with urgency.',
        'Decide fast. Act faster.',
        'This is the work. Do it.',
        'Push through.',
        'Get it done.',
        'Take control now.',
        'Stop stalling.',
        'Execution is mandatory.',
        'Your effort decides the outcome.',
        'Begin the task.',
        'Drop the excuse.',
        'Move forward.',
        'Commit fully.',
        'Finish strong.',
        'No more hesitation.',
        'Act with intensity.',
        'Start the clock.',
        'Drive the action.',
        'Get serious.',
        'Handle it.',
        'Do not quit.',
        'Push harder.',
        'Stay on task.',
        'Take the step.',
        'Make it happen.',
        'Stay focused.',
        'Control the moment.',
        'Advance.',
        'Follow through.',
        'Execute cleanly.',
        'Work now.',
        'Break inertia.',
        'Push past resistance.',
        'Get moving.',
        'Deliver.',
        'Take charge.',
        'End procrastination.',
        'Act decisively.',
        'Finish the job.',
        'Move immediately.',
        'Own the effort.',
        'Stay disciplined.',
        'Complete the task.',
        'Stop delaying.',
        'Do the thing.',
        'Execute until done.',
        'Prove it with action.',
        'Get after it.',
      ],
    ),
    BotArchetype(
      id: 'gentle_guide_bestie',
      displayName: 'Gentle Guide Bestie',
      description: 'Warm, caring support from someone in your corner.',
      messages: [
        'It’s okay to start small. Small still counts.',
        'You don’t have to do everything today—just one kind thing for your goal.',
        'Take a breath. You can begin gently.',
        'Showing up imperfectly is still showing up.',
        'You’re allowed to move at a pace that feels sustainable.',
        'One small step is enough for now.',
        'You don’t need pressure to make progress.',
        'It’s okay if today looks different than you planned.',
        'Be kind to yourself and take the next step.',
        'You’re doing better than you think.',
        'Progress doesn’t have to hurt to matter.',
        'You can take this one piece at a time.',
        'Rest and effort can coexist.',
        'You don’t need to rush—just don’t disappear.',
        'Doing a little today helps tomorrow feel lighter.',
        'It’s safe to begin without having it all figured out.',
        'You can move forward without being hard on yourself.',
        'Your effort matters, even when it’s quiet.',
        'You don’t have to prove anything to keep going.',
        'Consistency grows from compassion.',
        'It’s okay to take breaks and still care about your goal.',
        'You’re allowed to start again without guilt.',
        'Soft progress is still progress.',
        'You don’t need to feel confident to take a step.',
        'Let this be gentle, not perfect.',
        'You can do this in a way that respects your energy.',
        'Kindness toward yourself builds momentum.',
        'You’re not behind—you’re just human.',
        'It’s okay if today’s step is smaller than yesterday’s.',
        'You’re allowed to take up space at your own pace.',
        'Nothing is wrong with moving slowly.',
        'You don’t need to push—just nudge yourself forward.',
        'Your effort is enough for today.',
        'You can pause without quitting.',
        'Take the pressure off and begin anyway.',
        'You’re learning as you go, and that’s okay.',
        'Doing your best looks different every day.',
        'You don’t need to compare your pace to anyone else’s.',
        'Be patient with yourself while you grow.',
        'Your goal doesn’t need suffering to be meaningful.',
        'You’re allowed to protect your energy.',
        'Try again, gently.',
        'One calm step can change the day.',
        'You’re allowed to feel tired and still care.',
        'It’s okay to choose ease where possible.',
        'Progress can be quiet and kind.',
        'You don’t need to earn rest.',
        'Give yourself permission to go slowly.',
        'You’re doing something meaningful just by continuing.',
        'You don’t need to force this.',
        'Your pace is allowed.',
        'You can take the next step without pressure.',
        'You don’t have to be perfect to be consistent.',
        'Let today be manageable.',
        'You’re allowed to do this gently.',
        'Kind effort counts.',
        'You can make progress without overwhelm.',
        'It’s okay if this feels hard sometimes.',
        'You’re showing up in the best way you can.',
        'One soft step still moves you forward.',
        'You don’t need to push past your limits today.',
        'Care for yourself while you work toward this.',
        'You’re allowed to listen to your body.',
        'Your goal can grow with you.',
        'You don’t have to finish—just begin.',
        'Progress doesn’t require self-criticism.',
        'You can take today at your own pace.',
        'Being gentle doesn’t mean you’re giving up.',
        'You’re allowed to move forward with kindness.',
        'You don’t need to rush to be worthy.',
        'Slow progress still builds something real.',
        'You can choose steadiness over stress.',
        'It’s okay to keep this light.',
        'You’re doing enough for today.',
        'You can continue tomorrow.',
        'Trust yourself to take the next gentle step.',
        'You’re allowed to be proud of small wins.',
        'Nothing is wasted when you show up with care.',
        'You don’t have to push through everything.',
        'Your effort is valid.',
        'Be kind. Keep going.',
        'You’re allowed to move forward softly.',
        'You can do this without hurting yourself.',
        'Let progress feel supportive.',
        'You’re safe to keep going.',
        'One step at a time is enough.',
        'You’re doing something good for yourself.',
        'It’s okay to move gently and still move.',
        'Today’s effort matters.',
        'You don’t have to be hard to be strong.',
        'You can keep going—with kindness.',
      ],
    ),
    BotArchetype(
      id: 'mindful_millionaire',
      displayName: 'Mindful Millionaire',
      description: 'Build wealth with intention and a clear mind.',
      messages: [
        'Think like a wealth builder today: focus on the one action that increases income, assets, or opportunity and do it first. Money compounds from disciplined action.',
        'Multi-millionaires win through consistent value creation. Complete the task today that most directly increases revenue or opportunity.',
        'Make a move today that your future wealthy self would thank you for. Small financial progress compounds into large wealth.',
        'Treat your focus like financial capital. Invest your time in actions that grow income, assets, or opportunity.',
        'Progress builds wealth faster than perfection. Take the next step today that moves you closer to financial growth.',
        'Wealth is built through smart daily decisions. Make one move today that improves your financial future.',
        'Do the income-producing work first today. Wealth builders prioritize actions that grow opportunity.',
        'Ask yourself: what would a financially successful person do with this hour? Use it to create value.',
        'Your daily habits are building your financial life. Choose actions today that grow income, skills, or assets.',
        'Focus on creating value people will pay for today. Money follows useful solutions.',
        'Think like an owner today. What action increases your income or assets?',
        'Wealth grows from value creation. Build something useful today.',
        'Protect your time like capital. Spend it on things that produce returns.',
        'Ask: what action today could increase my future income? Start there.',
        'Millionaires prioritize leverage. Do the work that multiplies results.',
        'Turn ideas into assets today. Execution creates wealth.',
        'Focus on income-producing activities first today.',
        'Your habits today are building your financial future.',
        'Spend less time consuming and more time creating value.',
        'Ask yourself: what can I build today that earns tomorrow?',
        'Wealth rewards those who create solutions. Solve something today.',
        'Invest your effort where it can grow into opportunity.',
        'Think in terms of assets, not hours.',
        'One smart financial decision today compounds for years.',
        'Treat your attention like money. Invest it wisely.',
        'Build something today that increases your long-term earning power.',
        'Millionaire thinking asks: how can this scale?',
        'Focus on opportunity, not obstacles.',
        'Your next opportunity may begin with today’s effort.',
        'Build income streams, not just tasks.',
        'Every day is a chance to strengthen your financial future.',
        'Think beyond today’s paycheck. Build tomorrow’s assets.',
        'Focus on actions that produce measurable results.',
        'Wealth grows where consistent effort meets smart decisions.',
        'Choose growth opportunities over comfortable routines.',
        'Ask: what skill today increases my earning power?',
        'Money follows value. Create more of it today.',
        'Look for leverage in everything you do today.',
        'Turn knowledge into opportunity today.',
        'Financial success starts with disciplined daily action.',
        'Invest time learning something that improves your income potential.',
        'Make one move today that strengthens your financial position.',
        'Build systems, not just effort.',
        'Focus on opportunities that compound over time.',
        'Millionaires look for scalable results. Think bigger today.',
        'Turn effort into assets whenever possible.',
        'Improve something today that could increase revenue tomorrow.',
        'Build something today that works even when you rest.',
        'Treat every day like an opportunity to grow wealth.',
        'Spend time where returns are highest.',
        'Look for opportunities others overlook.',
        'Make progress toward financial independence today.',
        'Wealth grows through consistent smart action.',
        'Create more value than you consume today.',
        'Focus on building, investing, or improving something profitable.',
        'Ask what could multiply your effort today.',
        'Think long-term wealth, not short-term comfort.',
        'Improve one income skill today.',
        'Seek opportunities that create recurring value.',
        'Build the mindset of financial ownership today.',
        'Turn effort into progress toward wealth.',
        'Focus on results that increase opportunity.',
        'Wealth builders act while others wait.',
        'Improve your financial knowledge today.',
        'One smart move today can pay dividends later.',
        'Look for ways to turn skills into income.',
        'Build value others are willing to pay for.',
        'Spend your energy where it grows opportunity.',
        'Think in terms of long-term wealth creation.',
        'Focus on building something valuable today.',
        'Look for opportunities to create leverage.',
        'Build the habit of thinking like an investor.',
        'Turn effort into something that lasts.',
        'Create progress that improves your financial future.',
        'Focus on opportunities that scale.',
        'Ask how today’s work can create future income.',
        'Make decisions that strengthen your financial path.',
        'Grow your ability to create value today.',
        'Look for problems that people will pay to solve.',
        'Wealth favors disciplined builders.',
        'Spend time on work that grows opportunity.',
        'Turn ideas into execution today.',
        'Build something that increases your leverage.',
        'Invest your attention in opportunity.',
        'Create progress toward financial freedom today.',
        'Look for ways to multiply results.',
        'Strengthen the habits of a wealth builder.',
        'Focus on opportunities that grow over time.',
        'Improve your financial trajectory today.',
        'Build momentum toward wealth.',
      ],
    ),
    BotArchetype(
      id: 'observational_comedian',
      displayName: 'Observational Comedian',
      description: 'Light-hearted laughs to keep the journey fun.',
      messages: [
        'Funny how you’re waiting for the perfect moment. Those never RSVP.',
        'You’ve thought about this longer than it would take to start.',
        'Interesting strategy: doing nothing and hoping progress appears.',
        'You don’t need motivation—you need five minutes and less drama.',
        'Notice how avoiding this hasn’t improved it at all.',
        'You’ve survived harder things than starting this.',
        'At some point, planning becomes a hobby. This is that point.',
        'You’re not overwhelmed—you’re just allergic to starting.',
        'If effort were embarrassing, this would still be worth it.',
        'Wild idea: try the thing before judging it.',
        'You’ve spent more energy resisting this than doing it would take.',
        'This doesn’t require confidence. It requires movement.',
        'Procrastination is just fear wearing sweatpants.',
        'You don’t have to like this. You just have to begin.',
        'Nothing about starting commits you to finishing today.',
        'You can stop anytime—after you start.',
        'Funny how clarity always shows up after action, not before.',
        'This task isn’t judging you. You’re doing that part.',
        'You’ve definitely done dumber things than this.',
        'The bar is low. Step over it.',
        'If this were easy, you’d already be done complaining.',
        'You don’t need a mood. You need momentum.',
        'This counts even if it’s messy.',
        'You’re allowed to do this badly at first.',
        'At no point will future-you thank you for waiting.',
        'You’re not stuck. You’re paused with opinions.',
        'Starting now is still on time.',
        'You can make progress without making announcements.',
        'Nothing dramatic happens when you begin. That’s the point.',
        'One imperfect step beats another perfect excuse.',
        'You don’t need inspiration—you need less delay.',
        'Resistance always sounds smarter than it is.',
        'You’ve already decided this matters. Act like it.',
        'This will feel lighter once it’s moving.',
        'You don’t have to win today. Just participate.',
        'Starting doesn’t lock you in—it lets you out.',
        'You’ve talked yourself out of this long enough.',
        'Progress is rarely loud. Begin quietly.',
        'You can stop overthinking now. This is the cue.',
        'You’re waiting for confidence like it’s a delivery.',
        'Nothing changes while you’re negotiating with yourself.',
        'You’ve scrolled past harder work than this.',
        'Doing a little now beats regretting it later.',
        'You don’t need a breakthrough. You need a beginning.',
        'Every excuse sounds reasonable until nothing happens.',
        'You’re not behind—you’re just not moving yet.',
        'This task won’t bite. It barely has teeth.',
        'Momentum doesn’t require enthusiasm.',
        'You’ve already wasted enough time explaining why not.',
        'The longer you wait, the heavier it feels. Curious.',
        'Starting badly is still starting.',
        'You’re not required to be impressive here.',
        'Perfection is just procrastination in a tuxedo.',
        'Nothing about this needs to be dramatic.',
        'You’ve delayed this so long it’s basically a tradition.',
        'Progress doesn’t care about your mood.',
        'You’re arguing with yourself again. Try acting instead.',
        'Five minutes from now could look very different.',
        'This task isn’t personal. Relax.',
        'You’ve already accepted this matters. Do the math.',
        'Thinking about it isn’t the same as doing it.',
        'You don’t need permission from future-you.',
        'The clock is moving whether you are or not.',
        'Doing something counts. Even if it’s not pretty.',
        'You can complain later—after progress.',
        'This is smaller than you’re making it.',
        'Nothing magical happens by waiting longer.',
        'You’ve been here before. Starting worked then too.',
        'You don’t need clarity to begin. Beginning creates clarity.',
        'This doesn’t need to feel good to be useful.',
        'You’ve delayed this enough to know it doesn’t help.',
        'Effort now saves explanation later.',
        'You’re not tired—you’re undecided.',
        'The task hasn’t changed. Only the avoidance has.',
        'You’re capable of starting things without fanfare.',
        'Starting is not a commitment—it’s a test.',
        'You don’t need to be ready. You need to move.',
        'Overthinking has had its turn.',
        'Future-you is quietly rooting for action.',
        'This moment is usable.',
        'You’re allowed to begin without a plan.',
        'Nothing improves by being ignored longer.',
        'You don’t need to fix everything—just begin something.',
        'This doesn’t require courage. It requires motion.',
        'You’ve done harder things accidentally.',
        'Waiting hasn’t improved the odds so far.',
        'You can stop negotiating now.',
        'Progress doesn’t announce itself.',
        'You’re not late—you’re just early to starting.',
        'This is manageable once it’s moving.',
        'You don’t need certainty to begin.',
        'Begin before your brain changes its mind.',
        'You’ve reached the part where action helps.',
        'Less thinking. More doing.',
        'This is the moment you start.',
      ],
    ),
    BotArchetype(
      id: 'stoic_mentor',
      displayName: 'Stoic Mentor',
      description: 'Ancient wisdom for modern discipline.',
      messages: [
        'Focus on what is within your control. Begin there.',
        'You cannot control outcomes—only your actions. Act well.',
        'Do the next right thing, without attachment to the result.',
        'Progress comes from consistency, not urgency.',
        'What stands in the way becomes the way—if you engage it calmly.',
        'Let go of what you cannot influence. Apply effort where you can.',
        'This moment is sufficient for action.',
        'Do not wait for conditions to improve. Improve your response.',
        'Act according to principle, not mood.',
        'Small, deliberate actions shape character over time.',
        'You are not disturbed by events, but by your judgments about them.',
        'Choose reason over reaction.',
        'Begin without complaint. Continue without expectation.',
        'Discipline is freedom practiced daily.',
        'Accept the difficulty. Then proceed.',
        'You need not rush. You need not stop.',
        'Let effort be your measure of success.',
        'What you do repeatedly becomes who you are.',
        'Calm action outlasts emotional intensity.',
        'Attend to the task before you.',
        'Release the need for immediate reward.',
        'Act as if your future self is watching.',
        'Delay weakens resolve. Begin now, quietly.',
        'You can endure more than you imagine—especially calmly.',
        'Remove excess. Focus on what matters.',
        'Simplicity strengthens resolve.',
        'Your power lies in choice, not circumstance.',
        'Meet resistance with steadiness, not force.',
        'The path clears through action.',
        'Progress favors patience.',
        'Do not argue with the task. Engage it.',
        'Act without seeking approval.',
        'Consistent effort is enough.',
        'What matters is what you do next.',
        'Let today be sufficient.',
        'Carry yourself with quiet resolve.',
        'You may begin again, without self-reproach.',
        'Steady effort outperforms bursts of intensity.',
        'Maintain your standards even when unseen.',
        'Your character is shaped in small moments like this one.',
        'Do not add suffering by resisting reality.',
        'Accept the present task as training.',
        'Act deliberately, not dramatically.',
        'You are capable of sustained effort.',
        'The work does not need to be perfect—only honest.',
        'Move forward with composure.',
        'Practice patience through action.',
        'Let reason guide the next step.',
        'Attend fully to what you are doing.',
        'Progress is quiet and cumulative.',
        'You are not required to feel ready.',
        'Begin with what is available.',
        'Time will pass regardless. Use it well.',
        'Choose effort over excuse.',
        'Let go of comparison. Return to your task.',
        'A calm mind executes more effectively.',
        'You have done difficult things before. Proceed.',
        'Stay with the work.',
        'Resolve is strengthened through repetition.',
        'Act without resentment.',
        'What is essential can be done simply.',
        'Reduce the task to its essence.',
        'Move forward without haste or hesitation.',
        'You can act well even when circumstances are imperfect.',
        'Choose progress over protest.',
        'The present effort is sufficient.',
        'Do not wait for motivation. Practice discipline.',
        'Your response defines the outcome you can influence.',
        'Do not abandon the task because it feels difficult.',
        'Engage with steadiness.',
        'Each action is a vote for the person you are becoming.',
        'Act as a student of effort.',
        'Let the work teach you.',
        'Persist without bitterness.',
        'Maintain focus on what is necessary.',
        'You may proceed calmly.',
        'Nothing prevents you from taking the next step.',
        'The work requires attention, not emotion.',
        'Choose composure over complaint.',
        'Act with dignity.',
        'Do not postpone what can be done now.',
        'The task is manageable when approached steadily.',
        'Practice restraint in thought and action.',
        'Direct your energy wisely.',
        'Stay aligned with your principles.',
        'You are strengthened by consistent effort.',
        'Do not resist the discipline that supports you.',
        'Each moment offers an opportunity for virtue.',
        'Return to the task without judgment.',
        'Endure calmly. Continue deliberately.',
        'The value lies in the effort itself.',
        'Maintain clarity under pressure.',
        'You are capable of sustained focus.',
        'Let go of urgency. Keep direction.',
        'Proceed with patience.',
        'You are training your character through action.',
        'Act in accordance with reason.',
        'Let consistency be your strength.',
        'Do what is required, quietly.',
        'Begin again—calmly and without delay.',
      ],
    ),
    BotArchetype(
      id: 'boardroom_ceo',
      displayName: 'Boardroom CEO',
      description: 'Strategic leadership thinking for your personal goals.',
      messages: [
        'CEOs don’t wait to feel ready. They execute based on decision. What is the smallest action that moves this forward right now?',
        'If this goal mattered, it would be on today’s agenda. Schedule the next action like a board meeting—non-negotiable.',
        'Progress doesn’t come from intensity—it comes from consistency. One deliberate step today protects momentum.',
        'No one is coming to manage this for you. Ownership is the advantage. Decide. Act. Review.',
        'Measure what matters. After today’s action, ask: did this move the needle—even slightly?',
        'Decide once. Remove the debate. Action follows clarity.',
        'The first action sets the tone. What starts this—not finishes it?',
        'You don’t need more time or tools. Use what’s already in front of you.',
        'If time were limited, what would you do first? Do that.',
        'What is pulling attention away from execution? Eliminate one distraction now.',
        'Ignore outcomes. Control the next action.',
        'Pressure isn’t a signal to stop. It’s a signal to simplify.',
        'Protect one block of time today. That block moves the goal forward.',
        'Do this to a professional standard—not a perfect one.',
        'Execution improves when energy is managed. Reset, then proceed.',
        'What proof exists that progress was made today?',
        'Extract one lesson. Apply it tomorrow.',
        'Close the loop. Completion creates momentum.',
        'Act like the person responsible for results—because you are.',
        'Short-term discomfort protects long-term leverage.',
        'If the goal feels heavy, it’s unclear. Define the next move in one sentence.',
        'Choose one metric that defines progress today. Ignore the rest.',
        'Use the next 15 minutes deliberately. Small blocks compound.',
        'Shrink the task until it’s undeniable. Then execute.',
        'Action beats planning at this stage. Move.',
        'If it isn’t on the calendar, it isn’t a priority. Schedule it now.',
        'The task you’re avoiding is likely the one that matters most.',
        'When unsure, act. Information follows movement.',
        'Raise or lower the standard—just don’t stall. Progress requires motion.',
        'No announcements. No validation. Execute.',
        'Is this a reversible decision? If yes, decide quickly.',
        'Three priorities dilute focus. Choose one.',
        'Plan. Execute. Review. Adjust. Repeat.',
        'Direct energy toward progress, not explanation.',
        'What would this look like if it were simple?',
        'Protect what’s already working. Build from there.',
        'You have permission to proceed. Take it.',
        'Remove one obstacle between you and execution.',
        'Pause briefly to align—then move decisively.',
        'Close today with a win, however small.',
        'Save energy for execution. Decide once and move.',
        'What actually advances the goal? Do only that.',
        'Which action creates the highest return today? Start there.',
        'If there’s no deadline, create one. Urgency clarifies.',
        'Make progress visible—even if it’s small.',
        'Remove complexity. Straight lines move faster.',
        'You’re not waiting for permission. Proceed.',
        'Work on one thing until it’s meaningfully advanced.',
        'Notice the resistance. Then act anyway.',
        'Own the next block of time. Use it deliberately.',
        'Treat this like a paid responsibility.',
        'Rough execution beats refined delay.',
        'Reduce options. Increase action.',
        'Don’t break the chain. One step keeps momentum alive.',
        'Know what ‘done’ looks like before you begin.',
        'Reset focus. Execute the next step cleanly.',
        'Temporary discomfort is part of leadership.',
        'Protect the goal from interruption.',
        'Keep the long view while executing the short move.',
        'Finish one thing before starting another.',
        'When analysis stalls, action restores clarity.',
        'Move in the right direction before worrying about pace.',
        'This outcome has an owner. It’s you.',
        'Do the part you’re postponing—now.',
        'Create one visible sign of progress today.',
        'Limit the task to what can be completed in one sitting.',
        'Recommit to the goal. Then act once.',
        'Nothing else matters until this step is complete.',
        'Make the decision smaller so it can be made immediately.',
        'Set a short time box and execute without interruption.',
        'Don’t stop at comfort. Advance one step further.',
        'If this were easy, what would you do first?',
        'Calm focus produces better outcomes than urgency.',
        'Meet the standard required—no more, no less.',
        'Decide. Act. Review. Repeat.',
        'Remove one distraction before continuing.',
        'This action exists to serve the result. Keep it aligned.',
        'Begin before you feel fully prepared.',
        'Under pressure, reduce options. Execute the best one.',
        'Anchor today to one meaningful action.',
        'Lead yourself through this step.',
        'Finish what’s in front of you.',
        'Put full attention on this task for a short window.',
        'Consider the cost of waiting. Then proceed.',
        'You control the next move. Take it.',
        'This is the window. Use it.',
        'Do less. Do it deliberately.',
        'Progress compounds when action is daily.',
        'Choose a direction and commit to the step.',
        'Clarity improves after movement, not before.',
        'Frame this as a decision, not a burden.',
        'Treat this time as valuable. Act accordingly.',
        'Protect this task from dilution.',
        'Act like the leader responsible for delivery.',
        'Establish a rhythm. Follow it today.',
        'Lower the friction to starting. Begin.',
        'Confirm direction, then move without hesitation.',
        'Close this step cleanly before moving on.',
        'Trust progress built through repetition.',
        'Complete one meaningful action before stopping.',
      ],
    ),
    BotArchetype(
      id: 'voice_of_enough',
      displayName: 'The Voice of Enough',
      description: 'You are enough. Rest is not failure.',
      messages: [
        'Not everything valuable can be counted in dollars.',
        'Character builds a life that money cannot buy.',
        'Do the work because it matters, not because it pays.',
        'A peaceful mind is worth more than a full wallet.',
        'Build a life you respect, not just one that earns.',
        'Wealth of character outlasts wealth of money.',
        'Some of the best things in life never appear on a bill.',
        'Choose purpose over profit today.',
        'True success is the life you live, not the income you show.',
        'Invest time in people, not just outcomes.',
        'Integrity is a currency that never loses value.',
        'Respect cannot be purchased. It must be earned.',
        'The most meaningful work often has no price tag.',
        'Money can buy comfort, but not meaning.',
        'Measure your life by impact, not income.',
        'Focus on what lasts longer than money.',
        'Peace of mind is a priceless asset.',
        'The right path is not always the most profitable one.',
        'Value the work that builds character.',
        'Let purpose guide your effort today.',
        'A good life is built through values, not transactions.',
        'Wealth of spirit outlasts material wealth.',
        'Protect your integrity more than your income.',
        'The best investments are often invisible.',
        'Time spent well is worth more than money earned quickly.',
        'Choose meaning when profit tries to distract you.',
        'Relationships are a richer currency.',
        'What you give to others is never wasted.',
        'Leave something valuable behind that cannot be sold.',
        'Work for pride in your craft.',
        'Success is living in alignment with your values.',
        'Build something useful, not just profitable.',
        'A quiet life with purpose beats a loud life with money.',
        'Seek fulfillment over financial applause.',
        'Care for what truly matters today.',
        'Let your work serve people, not just profit.',
        'Respect the things that cannot be bought.',
        'Live in a way that future you will admire.',
        'Wealth of heart is deeper than wealth of money.',
        'Build strength that money cannot replace.',
        'Choose dignity over profit when they conflict.',
        'Value your time more than your earnings.',
        'Meaningful effort is its own reward.',
        'Live simply and purposefully.',
        'The right path is often quieter than the profitable one.',
        'Invest in wisdom and health.',
        'Choose contribution over accumulation.',
        'Do good work even when it does not pay more.',
        'Measure success by the lives you improve.',
        'A meaningful life is the greatest wealth.',
      ],
    ),
    BotArchetype(
      id: 'the_steward',
      displayName: 'The Steward',
      description: 'Build something worth leaving behind.',
      messages: [
        'Care for something living today.',
        'Patience is a form of strength. Practice it.',
        'Protect your attention from what weakens it.',
        'The quiet work still matters.',
        'Be the calm person in a noisy moment.',
        'A good steward improves the ordinary.',
        'Honor the time you were given today.',
        'Speak in a way that strengthens others.',
        'Maintain what others overlook.',
        'Character grows through repetition.',
        'Keep your word even when it is inconvenient.',
        'Do one task slowly and well.',
        'Notice something beautiful you usually ignore.',
        'Let your presence bring steadiness.',
        'Restore order where you can.',
        'Guard your mind from unnecessary negativity.',
        'The smallest duties reveal the strongest character.',
        'Leave something cleaner than you found it.',
        'Let discipline guide your choices today.',
        'Treat your body with respect.',
        'Listen fully when someone speaks.',
        'Build patience into your day.',
        'Be dependable without seeking recognition.',
        'Quiet consistency builds lasting strength.',
        'Protect what is good around you.',
        'Respond instead of reacting.',
        'Steward your emotions wisely.',
        'Be grateful for simple stability.',
        'Strength often looks like restraint.',
        'Care for your responsibilities first.',
        'Respect the effort behind everything useful.',
        'Improve your environment with small actions.',
        'Let kindness be deliberate today.',
        'Guard your integrity carefully.',
        'Build habits that make tomorrow easier.',
        'Choose calm over urgency.',
        'Steward your energy wisely.',
        'Let patience shape your decisions.',
        'Strength grows through quiet discipline.',
        'Honor the ordinary tasks.',
        'Protect your peace from unnecessary conflict.',
        'Encourage someone without expecting anything back.',
        'Use your time intentionally.',
        'Stand steady when others rush.',
        'Be thoughtful with your words.',
        'A steward leaves people stronger.',
        'Practice humility when you succeed.',
        'Practice resilience when things fail.',
        'Improve one thing you rely on.',
        'Pay attention to what truly matters.',
        'Build trust through consistent action.',
        'The way you live teaches others.',
        'Protect your focus today.',
        'Let patience guide your work.',
        'Repair something small.',
        'Do not neglect the basics.',
        'Value reliability over recognition.',
        'Build something useful today.',
        'Choose progress over perfection.',
        'Quiet effort creates strong foundations.',
        'Keep learning even when it is difficult.',
        'Stewardship means caring for the future.',
        'Improve your habits slowly but steadily.',
        'Respect the limits of your energy.',
        'Honor the responsibilities you carry.',
        'Leave wisdom where you can.',
        'Choose steadiness over excitement.',
        'Protect the things that matter most.',
        'Make thoughtful decisions.',
        'Lead by example.',
        'Speak truth calmly.',
        'Give your best attention to the present moment.',
        'Care for your surroundings.',
        'Build something that lasts.',
        'Value patience over speed.',
        'Strengthen your discipline quietly.',
        'Keep your promises.',
        'Improve your environment with intention.',
        'Choose responsibility over ease.',
        'Protect your integrity at all times.',
        'The future benefits from today’s care.',
        'Respect the effort of others.',
        'Practice gratitude often.',
        'Restore balance where you can.',
        'Honor the process of growth.',
        'Invest attention in meaningful work.',
        'Stay steady during uncertainty.',
        'Maintain what supports you.',
        'Care for your mental clarity.',
        'Build trust through honesty.',
        'Leave every conversation better.',
        'Steward your reactions carefully.',
        'Patience strengthens character.',
        'Use quiet moments wisely.',
        'Practice discipline in small ways.',
        'Protect the peace of your mind.',
        'Build strength gradually.',
        'Improve what you touch today.',
        'Honor the responsibility of influence.',
        'Leave the world slightly better.',
      ],
    ),
  ];

  static Future<void> seedToFirestoreIfEmpty() async {
    try {
      final firestore = FirebaseFirestore.instance;
      final snapshot = await firestore.collection('bots').limit(1).get();
      // if (snapshot.docs.isNotEmpty) {
      //   return;
      // }
      final batch = firestore.batch();
      for (final archetype in archetypes) {
        final ref = firestore.collection('bots').doc(archetype.id);
        batch.set(ref, archetype.toJson());
      }
      await batch.commit();
      print('Bot seed data written to Firestore.');
    } catch (e) {
      print('Error seeding bot data: $e');
    }
  }
}
